import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import ThemeProvider from "../container/ThemeProvider";

import "./globals.css";

const nunito = Nunito({
  weight: ["300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  dashboard, // login,
}: {
  dashboard: React.ReactNode;
  // login: React.ReactNode;
}) {
  // const loggedIn = false;
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ThemeProvider>{dashboard}</ThemeProvider>
      </body>
    </html>
  );
}
